const entities = [{"slug":"dana_petroleum","name":"Dana Petroleum","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":"Dana Petroleum Netherlands B.V.","registration_ref":"27120679","parent_company":"Dana Petroleum Limited","registry_link":"https://find-and-update.company-information.service.gov.uk/company/03456891/persons-with-significant-control","registry_place":"Register Verenigd Koninkrijk","legal_env":"VK","member":true}, 
{"slug":"ebn","name":"Energie Beheer Nederland","sector":"Olie & Gas - Staatsdeelneming","sector_en":"Oil & Gas -State Share","type":"company","trade_name":"EBN B.V.","registration_ref":"14026250","parent_company":"Nederlandse Staat","registry_link":null,"registry_place":null,"legal_env":"NL","member":true}, 
{"slug":"exxonmobil","name":"ExxonMobil","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":"ExxonMobil Producing Netherlands B.V. ","registration_ref":"20122275","parent_company":"Exxon Mobil Corporation","registry_link":"https://www.nasdaq.com/market-activity/stocks/xom/institutional-holdings","registry_place":"Nasdaq","legal_env":"VS","member":true}, 
{"slug":"frisia_zoutwinning","name":"Frisia Zoutwinning","sector":"Zoutwinning","sector_en":"Salt extraction","type":"company","trade_name":"Frisia Zout B.V.","registration_ref":"1089417","parent_company":"K+S Aktiengesellschaft","registry_link":"https://www.boerse-frankfurt.de/equity/k-s-aktiengesellschaft/company-details","registry_place":"Beurs van Frankfurt","legal_env":"DE","member":true}, 
{"slug":"jetex_petroleum","name":"Jetex Petroleum","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":"Jetex Petroleum Limited","registration_ref":"n.v.t.","parent_company":"Highland Petroleum Limited","registry_link":"https://find-and-update.company-information.service.gov.uk/company/08998681/persons-with-significant-control","registry_place":"Register Verenigd Koninkrijk","legal_env":"VK","member":true}, 
{"slug":"neptune_energy","name":"Neptune Energy","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":"Neptune Energy Netherlands B.V.","registration_ref":"27113806","parent_company":"Neptune Energy Group Limited","registry_link":"https://find-and-update.company-information.service.gov.uk/company/10647707/persons-with-significant-control","registry_place":"Register Verenigd Koninkrijk","legal_env":"VK","member":true}, 
{"slug":"rockrose_energy","name":"Rockrose","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":"RockRose (NL) CS1 B.V.","registration_ref":"30108055","parent_company":"Viaro Investment Limited","registry_link":"https://find-and-update.company-information.service.gov.uk/company/12369869/officers","registry_place":"Register Verenigd Koninkrijk","legal_env":"VK","member":true}, 
{"slug":"spirit_energy","name":"Spirit Energy","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":"Spirit Energy Nederland B.V.","registration_ref":"34081068","parent_company":"Spirit Energy Limited","registry_link":"https://find-and-update.company-information.service.gov.uk/company/10854461/persons-with-significant-control","registry_place":"Register Verenigd Koninkrijk","legal_env":"VK","member":true}, 
{"slug":"taqa","name":"Taqa Offshore","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":"TAQA Offshore B.V.","registration_ref":"27273135","parent_company":"Abu Dhabi National Energy Company - P.J.S.C.","registry_link":"https://www.adx.ae/english/pages/productsandservices/securities/selectcompany/company-info.aspx?listedcompanyid=TAQA&pnavTitle=TAQA","registry_place":"Beurs van Abu Dhabi","legal_env":"VAE","member":true}, 
{"slug":"total","name":"TotalEnergies","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":"TotalEnergies EP Nederland B.V.","registration_ref":"27075440","parent_company":"TotalEnergies SE","registry_link":"https://live.euronext.com/nl/product/equities/FR0000120271-XPAR/company-information","registry_place":"Beurs Parijs","legal_env":"FR","member":true}, 
{"slug":"vermilion_energy","name":"Vermilion Energy","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":"Vermilion Energy Netherlands B.V.","registration_ref":"34201179","parent_company":"Vermilion Energy Inc.","registry_link":"https://live.euronext.com/nl/product/equities/FR0000120271-XPAR/company-information","registry_place":"Nasdaq","legal_env":"VS","member":true}, 
{"slug":"hansa_hydrocarbons","name":"Hansa Hydrocarbons","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":true}, 
{"slug":"noordgastransport","name":"Noordgastransport","sector":"Olie & Gas - Transport","sector_en":"Oil & Gas - Transport","type":"company","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":true}, 
{"slug":"nobian_salt","name":"Nobian Salt","sector":"Zoutwinning","sector_en":"Salt extraction","type":"company","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":true}, 
{"slug":"company","name":"Winst uit gehele bedrijf","sector":null,"sector_en":null,"type":"misc","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":false}, 
{"slug":"nogat","name":"NOGAT","sector":"Olie & Gas - Transport","sector_en":"Oil & Gas - Transport","type":"company","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":true}, 
{"slug":"ezk","name":"Ministerie van Economische Zaken en Klimaat","sector":"Overheid","sector_en":null,"type":"gov","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":false}, 
{"slug":"tulip_oil","name":"Tulip Oil","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":true}, 
{"slug":"nedmag","name":"Nedmag","sector":"Zoutwinning","sector_en":"Salt extraction","type":"company","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":true}, 
{"slug":"wintershall","name":"Wintershall Noordzee","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":true}, 
{"slug":"one_dyas","name":"ONE-Dyas","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":true}, 
{"slug":"petrogas","name":"Petrogas","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":true}, 
{"slug":"belastingdienst","name":"Belastingdienst","sector":"Overheid","sector_en":null,"type":"gov","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":false}, 
{"slug":"activities","name":"Activiteiten van bedrijven in sector","sector":null,"sector_en":null,"type":"misc","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":false}, 
{"slug":"sodm","name":"Staatstoezicht op de Mijnen","sector":"Overheid","sector_en":null,"type":"gov","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":false}, 
{"slug":"nam","name":"Nederlandse Aardolie Maatschappij","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":true}, 
{"slug":"kistos","name":"Kistos","sector":"Olie & Gas - Exploratie & Productie","sector_en":"Oil & Gas - Exploration & Production","type":"company","trade_name":null,"registration_ref":null,"parent_company":null,"registry_link":null,"registry_place":null,"legal_env":null,"member":true}];

const members = entities.filter( e => e.member)


export default members;