
import { IGroupMappingV2 } from '../shared/interfaces';

const config : IGroupMappingV2[] = [
  {
    "slug" : "shares_in_economy",
    "ctrlr": "EconomySharesGroupV1",
    "graphs": [{
        "slug" : "ec_shares",
        "ctrlr" : "EconomySharesV1",
        "multiples" : "graphs",
        "args" : [],
        "parameters": [
        [
            {
                "label": "BBP mijnbouwsector",
                "label_en": "GDP",
                "column": "gdp_mining",
                "colour": "orange"
            },
            {
                "label": "BBP Nederland",
                "column": "gdp_total",
                "colour": "blue"
            },
        ],
        [
            {
                "label": "Overheidsinkomsten mijnbouwsector",
                "label_en": "Government revenues",
                "column": "gov_revenues_mining",
                "colour": "orange"
            },
            {
                "label": "Overheidsinkomsten Nederland",
                "column": "gov_revenues_total",
                "colour": "blue"
            },
        ],
        [
            {
                "label": "Uitvoer mijnbouwsector",
                "label_en": "Export",
                "column": "export_mining",
                "colour": "orange"
            },
            {
                "label": "Uitvoer Nederland",
                "column": "export_total",
                "colour": "blue"
            },
        ],
        [
            {
                "label": "Investeringen mijnbouwsector",
                "label_en": "Investments",
                "column": "investments_mining",
                "colour": "orange"
            },
            {
                "label": "Investeringen Nederland",
                "column": "investments_total",
                "colour": "blue"
            }
        ]
      ]}
    ],
    "header": "Omvang mijnbouwsector in Nederland",
    "header_en": "Size mining sector in the Netherlands",
    "functionality": ["shareTotalSelect","table","download"],
    "description": "<p>Om een idee te krijgen van de omvang van de mijnbouwsector in Nederland, wordt hier de sector uitgedrukt in een aantal economische variabelen. Ook kan de omvang voor alle sectoren en het percentage van de mijnbouwsector in de Nederlandse economie worden bekeken. De gegevens zijn gegenereerd door het Centraal Bureau voor de Statistiek. Hiermee wordt invulling gegeven aan vereiste 6.3 van de EITI Standaard.<p>",
    "description_en": "<p>To get an idea of ​​the size of the mining sector in the Netherlands, the sector is expressed here in a number of economic variables. The size for all sectors and the percentage of the mining sector in the Dutch economy can also be viewed. The data was generated by Statistics Netherlands. This fulfills requirement 6.3 of the EITI Standard.</p>",
    "endpoints": ["economy"],
    "segment": "mijnbouwsector"
  },
  {
        "slug" : "employment_in_economy",
        "ctrlr": "EconomyEmploymentGroupV1",
        "graphs": [{
            "slug" : "employment",
            "ctrlr" : "EconomyEmploymentV1",
            "args" : [],
            "parameters": [
                [
                    {
                        "label": "Werkgelegenheid mannen in mijnbouw ",
                        "column": "employment_mining_males",
                        "colour": "orange"
                    },
                    {
                        "label": "Werkgelegenheid vrouwen in mijnbouw",
                        "column": "employment_mining_females",
                        "colour": "blue"
                    },
                    {
                        "label": "Werkgelegenheid mannen in Nederland",
                        "column": "employment_total_males",
                        "colour": "green"
                    },
                    {
                        "label": "Werkgelegenheid vrouwen in Nederland",
                        "column": "employment_total_females",
                        "colour": "green"
                    }
                ]
            ]
        }],
        "header": "Werkgelegenheid mijnbouwsector Nederland",        
        "header_en": "Employment mining sector in the Netherlands",
        "functionality": ["shareTotalSelect","table","download"],
        "description": "<p>Ook de werkgelegenheid geeft een idee van de omvang van de mijnbouwsector. Ook kan de werkgelegenheid voor alle sectoren en het percentage van de mijnbouwsector in de Nederlandse economie worden bekeken. Daarbij wordt ook de verhouding man/vrouw weergegeven. De gegevens zijn gegenereerd door het Centraal Bureau voor de Statistiek. Hiermee wordt invulling gegeven aan vereiste 6.3 van de EITI Standaard.</p>",
        "description_en": "<p>Employment also gives an idea of ​​the size of the mining sector. Employment for all sectors and the percentage of the mining sector in the Dutch economy can also be viewed. The male/female ratio is also shown. The data was generated by Statistics Netherlands. This fulfills requirement 6.3 of the EITI Standard.</p>",
        "endpoints": ["economy"],
        "segment": "mijnbouwsector",
    },
    {
        "slug" : "productie_vs_export",
        "ctrlr": "EconomyProdGroupV1",
        "graphs" : [{
            "slug": "import_export",
            "ctrlr": "EconomyBarsV1",
            "multiples": "graphs",
            "args" : [],
            "parameters": [
                [
                    {
                        "label": "Ruwe aardolie en ruwe olie uit bitumineuze mineralen (2709)",
                        "label_en": "Petroleum oils and oils obtained from bituminous minerals, crude (2709)",
                        "column": "prod_2709_volume",
                        "colour": "orange"
                    },
                    {
                        "label": "Ruwe aardolie en ruwe olie uit bitumineuze mineralen (2709)",
                        "label_en": "Petroleum oils and oils obtained from bituminous minerals, crude (2709)",
                        "column": "prod_2709_price",
                        "colour": "orange"
                    },
                    {
                        "label": "Ruwe aardolie en ruwe olie uit bitumineuze mineralen (2709)",
                        "label_en": "Petroleum oils and oils obtained from bituminous minerals, crude (2709)",
                        "column": "export_2709_volume",
                        "colour": "blue"
                    },
                    {
                        "label": "Ruwe aardolie en ruwe olie uit bitumineuze mineralen (2709)",
                        "label_en": "Petroleum oils and oils obtained from bituminous minerals, crude (2709)",
                        "column": "export_2709_price",
                        "colour": "blue"
                    }
                ],
                [
                    {   
                        "label": "Aardgas en andere gasvormige koolwaterstoffen (2711)",
                        "label_en": "Petroleum gases and other gaseous hydrocarbons (2711)",
                        "column": "prod_2711_volume",
                        "colour": "orange"
                    },
                    {
                        "label": "Aardgas en andere gasvormige koolwaterstoffen (2711)",
                        "label_en": "Petroleum gases and other gaseous hydrocarbons (2711)",
                        "column": "prod_2711_price",
                        "colour": "orange"
                    },
                    {
                        "label": "Aardgas en andere gasvormige koolwaterstoffen (2711)",
                        "label_en": "Petroleum gases and other gaseous hydrocarbons (2711)",
                        "column": "export_2711_volume",
                        "colour": "blue"
                    },
                    {
                        "label": "Aardgas en andere gasvormige koolwaterstoffen (2711)",
                        "label_en": "Petroleum gases and other gaseous hydrocarbons (2711)",
                        "column": "export_2711_price",
                        "colour": "blue"
                    },
                ],
                [
                    {
                        "label": "Zout en zuiver natriumchloride (2501)",
                        "label_en": "Salt and pure sodium chloride (2501)",
                        "column": "prod_2501_volume",
                        "colour": "orange"
                    },
                    {
                        "label": "Zout en zuiver natriumchloride (2501)",
                        "label_en": "Salt and pure sodium chloride (2501)",
                        "column": "prod_2501_price",
                        "colour": "orange"
                    },
                    {
                        "label": "Zout en zuiver natriumchloride (2501)",
                        "label_en": "Salt and pure sodium chloride (2501)",
                        "column": "export_2501_volume",
                        "colour": "blue"
                    },
                    {
                        "label": "Zout en zuiver natriumchloride (2501)",
                        "label_en": "Salt and pure sodium chloride (2501)",
                        "column": "export_2501_price",
                        "colour": "blue"
                    }
                ]
            ]
        }],
        "header": "Productie en export van aardolie, aardgas en zout voor Nederland",
        "header_en": "Production and export of petroleum, natural gas and salt for the Netherlands",
        "functionality": ["priceVolumeSelect","table","download"],
        "description": "<p>De productie- en exportcijfers van de drie delfstoffen waarin de NL-EITI deelnemers actief zijn worden weergegeven voor Nederland. Dit zijn aardolie, aardgas en zout. Deze worden weergegeven op goederencode. Hiermee wordt invulling gegeven aan vereiste 3.2 en 3.3 van de EITI-Standaard. <p>",
        "description_en" : "<p>The production and export figures of the three minerals in which the NL-EITI participants are active are shown for the Netherlands. These are petroleum, natural gas and salt. These are displayed by commodity code. This fulfills requirements 3.2 and 3.3 of the EITI Standard.</p>",
        "endpoints": ["economy"],
        "segment": "prijs",
    },
    {
        "slug" : "environmental",
        "ctrlr": "EconomySocialGroupV1",
        "graphs" : [{
            "slug" : "energiebelasting",
            "ctrlr" : "EconomySocialV1",
            "multiples": "graphs",
            "args" : [],
            "parameters": [
                [
                    {
                        "label": "Afdracht energiebelasting",
                        "label_en": "Energy tax ",
                        "column": "energiebelasting",
                        "colour": "green",
                        "format" : "currency"
                    }
                ],
                [
                    {           
                        "label": "Opslag duurzame energie",
                        "label_en": "Surcharge for sustainable energy and climate transition",
                        "column": "milieubetaling_opslag",
                        "colour": "green",
                        "format" : "currency"
                    }
                ]
            ],
        }],
        "header": "Milieubelastingen",
        "header_en": "Unreconciled payments participants NL-EITI",
        "functionality": ["table","download"],
        "description": `
            <p>Nederland kent een aantal milieubelastingen, die worden geheven op grond van de Wet belastingen op milieugrondslag. Deze belastingen hebben tot doel het gebruik en verbruik van energie en milieubelastende goederen en diensten te belasten. Voor de E&P-bedrijven zijn de energiebelasting en de extra opslag duurzame energie- en klimaattransitie (ODE) voor duurzame energie relevant, die worden geheven op de levering van gas of elektriciteit aan verbruikers. Het tarief wordt berekend op basis van een aflopend bedrag per kubieke meter (gas) of kilowattuur (elektriciteit).</p>
            <p>Energiebelasting en de ODE worden in de regel niet door de E&P-bedrijven zelf aan de overheid afgedragen, maar door de energiebedrijven – de leveranciers van gas en elektriciteit. Deze bedrijven brengen de energiebelasting via de prijzen van gas en elektriciteit in rekening. Voor zover de E&P-bedrijven rechtstreeks gas en/of elektriciteit aan klanten leveren, brengen ook zij de energiebelasting en de ODE via de prijzen in rekening bij hun klanten. Om deze reden zijn de energiebelasting en de ODE niet meegenomen in de reconciliatie.</p>
            <p>Indien een gebruiker echter zelf energie opwekt om die te gebruiken op de plaats waar zij wordt opgewekt, moet die gebruiker de energiebelasting en de ODE zelf afdragen. Dit is bij E&P-bedrijven en zoutwinningsbedrijven soms het geval. Het E&P-bedrijf of het zoutbedrijf is dan de belastingbetaler. Er zijn op het bovenstaande vele uitzonderingen. Daarom zijn de rechtstreekse afdrachten van energiebelasting en ODE door E&P-bedrijven en zoutbedrijven aan de overheid niet materieel en vallen ze buiten de scope van de reconciliatie.</p>
            <p>De opslag duurzame energie- en klimaattransitie is in 2023 opgegaan in de energiebelasting.</p>`, 
        "description_en": `<p>The Netherlands charges a number of environmental taxes, which are levied under the Environmental Taxes Act (Wet belastingen op milieugrondslag). The aim is to tax the use and consumption of energy and environmentally harmful goods and services. The following taxes are relevant for E&P companies: the energy tax and the surcharge for sustainable energy and climate transition (ODE). These are levied on the supply of gas or electricity to consumers. The rate is calculated on the basis of a decreasing amount per cubic metre (gas) or kilowatt hour (electricity). 
        </p><p>Generally speaking, energy tax and the ODE are not paid to the government by the E&P companies themselves, but by the energy companies – the suppliers of gas and electricity. These companies charge the energy tax via the prices of gas and electricity. In as much as the E&P companies do supply gas and/or electricity directly to customers, they too charge the energy tax to their clients, via the prices. For this reason, the energy tax and ODE are not included in the reconciliation. However, if a user generates its own energy, for use at the location where it is generated, that user must itself pay the energy tax and the ODE. This is sometimes the case for E&P companies and salt companies. The E&P company or the salt company is then the tax payer. There are many exceptions to the above. 
        </p><p>For that reason, the direct payments of energy tax and ODE by E&P companies and salt companies to government are not material and are therefore beyond the scope of the reconciliation.</p>
        <p>In 2023 the surcharge for sustainable energy and climate transition has been included in the energy tax</p>`,
        "endpoints": ["economy"],
        "segment": "prijs",
    },
    {
        "slug" : "social",
        "ctrlr": "EconomySocialGroupV1",
        "graphs": [{
            
                "slug" : "sociale_betalingen",
                "ctrlr": "EconomySocialV1",
                "multiples": "graphs",
                "args" : [],
                "parameters": [
                    [
                        {
                            "label": "Sociale betalingen",
                            "label_en": "Social paytments",
                            "column": "sociale_betalingen",
                            "colour": "green",
                            "format" : "currency"
                        }
                    ]
                ]
        }],
        "header": "Sociale betalingen",
        "header_en": "Social payments",
        "functionality": ["table","download"],
        "description": `<p>Dit zijn alle bijdragen van winningsbedrijven aan de bevordering van de lokale ontwikkeling en de financiering van sociale projecten, overeenkomstig de EITI-Standaard. Deze Standaard moedigt multi-stakeholdergroepen ertoe aan om uiterst transparant te zijn over sociale betalingen en overdrachten, de bij die transacties betrokken partijen en de materialiteit van die betalingen en overdrachten voor andere bijdragestromen. Er moet onder andere op worden gelet dat over deze betalingen verslag gelegd kan worden, ook al zijn ze niet reconcilieerbaar.</p>
        <p>Volgens de definitie van de OESO bestaan sociale uitgaven uit bijdragen in contanten, rechtstreekse levering van goederen en diensten in natura, en belastingvoordelen met sociale doelstellingen. De bijdragen kunnen bedoeld zijn voor: huishoudens met een laag inkomen, ouderen, mensen met een handicap of ziekte of werklozen, of jongeren.</p>
        <p>Een programma is ‘sociaal’ als het gericht is op een herverdeling van middelen tussen huishoudens, of op verplichte deelname. De Mijnbouwwet voorziet niet in verplichte sociale betalingen. De verschillende stakeholders hebben dit bevestigd. Toch zijn er diverse bedrijven die op vrijwillige basis sociale activiteiten in Nederland ondersteunen.</p>
        `, 
        "description_en": `
            <p>These are all contributions from production companies aimed at promoting local development and the financing of social projects, in accordance with the EITI Standard. This standard encourages multi-stakeholder groups to be extremely transparent about social payments and transfers, the parties involved in these transactions and the materiality of those payments and transfers for other contribution streams. Amongst other things, attention must be paid to ensure that these payments can be reported on, even if they are not reconcilable</p>
            <p>According to the OECD definition, social payments consist of contributions in cash, direct supply of goods and services in kind, and tax benefits with social objectives. These contributions can be intended for: low-income households, the elderly, persons with a handicap or illness or the unemployed or young people.</p>  
            <p>A programme is considered ‘social’ if its purpose is to redistribute funds between households or compulsory participation. The Mining Act does not provide for compulsory social payments. This is confirmed by the various stakeholders. Nonetheless, a number of companies support activities in the Netherlands on a voluntary basis.</p>         
        `,
        "endpoints": ["economy"],
        "segment": "prijs"
    },
    {
        "slug" : "waterschappen",
        "ctrlr": "EconomySocialGroupV1",
        "graphs": [{
                "slug" : "waterschappen",
                "ctrlr": "EconomySocialV1",
                "multiples": "graphs",
                "args" : [],
                "parameters": [
                    [
                        {
                            "label": "Betalingen aan waterschappen",
                            "label_en": "Payments to water authorities",
                            "column": "betalingen_aan_waterschappen",
                            "colour": "green",
                            "format" : "currency"
                        }
                    ]
                ]
         }],
        "header": "Waterschapsbelasting en -heffingen",
        "header_en": "Water authority taxes and levies",
        "functionality": ["table","download"],
        "description": `<p>De Nederlandse waterschappen innen verschillende heffingen, waaronder een watersysteemheffing, een zuiveringsheffing en een verontreinigingsheffing. Welke belastingen een bedrijf betaalt, hangt af van de situatie van het bedrijf. NL-EITI MSG heeft besloten tot eenzijdige openbaarmaking door de meegewogen bedrijven van de aan de waterschappen afgedragen belastingen en heffingen.</p>`, 
        "description_en": "<p>The Dutch water authorities collect various levies including a water system levy, a purification levy and a contamination levy. The taxes to be paid by a company will depend on its situation. NL-EITI MSG has decided to unilaterally publish the taxes and levies paid by the companies included, to the water authorities.</p>",
        "endpoints": ["economy"],
        "segment": "prijs",
    }
];

export default config;